/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author lucas
 */
public class DatiInserimentoPopup extends javax.swing.JPanel {


    /**
     * Creates new form DatiInserimento
     */
    public DatiInserimentoPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruppoTipiValori = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ventoRB = new javax.swing.JRadioButton();
        pressioneRB = new javax.swing.JRadioButton();
        umiditaRB = new javax.swing.JRadioButton();
        temperaturaRB = new javax.swing.JRadioButton();
        precipitazioniRB = new javax.swing.JRadioButton();
        massaRB = new javax.swing.JRadioButton();
        altitudineRB = new javax.swing.JRadioButton();
        valoreRilevazione = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        valoreSlider = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        notePanel = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Inserimento Dati");

        ventoRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ventoRB.setText("Vento");

        pressioneRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pressioneRB.setText("Pressione");

        umiditaRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        umiditaRB.setText("Umidità");

        temperaturaRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        temperaturaRB.setText("Temperatura");

        precipitazioniRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        precipitazioniRB.setText("Precipitazioni");

        massaRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        massaRB.setText("Massa dei ghiacciai");

        altitudineRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        altitudineRB.setText("Altitudine dei ghiacciai");

        valoreRilevazione.setMaximum(5);
        valoreRilevazione.setMinimum(1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Valore:");

        valoreSlider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        valoreSlider.setText("x");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("<html>\n<p style=\"text-align: center\">Salva nuova <br/>rilevazione</p>");

        jScrollPane1.setViewportView(notePanel);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Le tue note:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precipitazioniRB)
                            .addComponent(ventoRB)
                            .addComponent(umiditaRB)
                            .addComponent(pressioneRB)
                            .addComponent(temperaturaRB)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valoreRilevazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valoreSlider))
                            .addComponent(massaRB)
                            .addComponent(altitudineRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ventoRB)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(umiditaRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pressioneRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(temperaturaRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(precipitazioniRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(altitudineRB))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(massaRB)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valoreRilevazione, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(valoreSlider))
                .addGap(59, 59, 59)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton altitudineRB;
    private javax.swing.ButtonGroup gruppoTipiValori;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton massaRB;
    private javax.swing.JTextPane notePanel;
    private javax.swing.JRadioButton precipitazioniRB;
    private javax.swing.JRadioButton pressioneRB;
    private javax.swing.JRadioButton temperaturaRB;
    private javax.swing.JRadioButton umiditaRB;
    private javax.swing.JSlider valoreRilevazione;
    private javax.swing.JLabel valoreSlider;
    private javax.swing.JRadioButton ventoRB;
    // End of variables declaration//GEN-END:variables

}
