/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClimateMonitoring;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Scanner;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author alesc
 */
public class NuovaRilevazionePopup extends javax.swing.JFrame {

    /**
     * Creates new form RilevazionePopup
     */
    public NuovaRilevazionePopup() {
        initComponents();
        gruppoTipoRilevazione.add(rbAltezzaG);
        gruppoTipoRilevazione.add(rbMassaG);
        gruppoTipoRilevazione.add(rbPrecip);
        gruppoTipoRilevazione.add(rbPress);
        gruppoTipoRilevazione.add(rbTemp);
        gruppoTipoRilevazione.add(rbUmid);
        gruppoTipoRilevazione.add(rbVento);
        xSlider.setText(""+valoreSlider.getValue());
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        String[] arrayLocalID=new String[4];
        try {
            FileReader read = new FileReader("datafiles/CentroMonitoraggio.csv");
            Scanner input = new Scanner(read);
            while(input.hasNextLine()) {
                String line = input.nextLine();
                String[] parts = line.split("#");
                    if (parts[0].equals(Utente.getCentro()))
                        arrayLocalID=parts[6].split("@");
                }
        }catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(rootPane, "Errore critico: impossibile trovare il fole contenente i centri di monitoraggio.");
        }
        ArrayList<String[]> datiLocalita= new ArrayList<String[]>();
        try {
                FileReader read = new FileReader("datafiles/CoordinateMonitoraggio.csv");
                Scanner input = new Scanner(read);
                while(input.hasNextLine()) {
                    String line = input.nextLine();
                    String[] parts = line.split("#");
                    for(String singoloID: arrayLocalID)
                        if(parts[0].equals(singoloID))
                            datiLocalita.add(parts);
                }
            }
        catch(FileNotFoundException ex){
                JOptionPane.showMessageDialog(rootPane, "Errore critico: impossibile trovare il file contenente le stazioni di monitoraggio.");
        }
        String[] coordinateTemp;
        for(String[] parti : datiLocalita)
        {
            coordinateTemp=parti[5].split(",");
            ddtm.addRow(
                new Object[] {parti[2],parti[4],parti[0],Double.valueOf(coordinateTemp[0]),Double.valueOf(coordinateTemp[1])});
        }
    }
    
    javax.swing.table.DefaultTableModel ddtm=new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
        "Località", "Stato", "ID", "Lat.", "Long."
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruppoTipoRilevazione = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbTemp = new javax.swing.JRadioButton();
        rbAltezzaG = new javax.swing.JRadioButton();
        rbPress = new javax.swing.JRadioButton();
        rbMassaG = new javax.swing.JRadioButton();
        rbPrecip = new javax.swing.JRadioButton();
        rbVento = new javax.swing.JRadioButton();
        rbUmid = new javax.swing.JRadioButton();
        valoreSlider = new javax.swing.JSlider();
        xSlider = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellaLocalita = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nomeLocalita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Nuova rilevazione");

        rbTemp.setText("Temperatura");

        rbAltezzaG.setText("Altezza dei ghiacciai");

        rbPress.setText("Pressione");

        rbMassaG.setText("Massa dei ghiacciai");

        rbPrecip.setText("Precipitazioni");

        rbVento.setText("Vento");

        rbUmid.setText("Umidità");

        valoreSlider.setMaximum(5);
        valoreSlider.setMinimum(1);
        valoreSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valoreSliderStateChanged(evt);
            }
        });

        xSlider.setText("X");

        jLabel3.setText("Valore:");

        tabellaLocalita.setModel(ddtm);
        tabellaLocalita.setColumnSelectionAllowed(true);
        tabellaLocalita.getTableHeader().setReorderingAllowed(false);
        tabellaLocalita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellaLocalitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabellaLocalita);
        tabellaLocalita.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabellaLocalita.getColumnModel().getColumnCount() > 0) {
            tabellaLocalita.getColumnModel().getColumn(0).setMinWidth(100);
            tabellaLocalita.getColumnModel().getColumn(0).setPreferredWidth(170);
            tabellaLocalita.getColumnModel().getColumn(0).setMaxWidth(250);
            tabellaLocalita.getColumnModel().getColumn(1).setMinWidth(100);
            tabellaLocalita.getColumnModel().getColumn(1).setPreferredWidth(170);
            tabellaLocalita.getColumnModel().getColumn(1).setMaxWidth(250);
            tabellaLocalita.getColumnModel().getColumn(2).setResizable(false);
            tabellaLocalita.getColumnModel().getColumn(2).setPreferredWidth(70);
            tabellaLocalita.getColumnModel().getColumn(3).setResizable(false);
            tabellaLocalita.getColumnModel().getColumn(3).setPreferredWidth(70);
        }

        jLabel4.setText("Le tue note:");

        jScrollPane2.setViewportView(jTextPane1);

        jLabel5.setText("Località dove è stata effettuata la rilevazione:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Annulla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Invia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbTemp)
                                    .addComponent(rbPress)
                                    .addComponent(rbPrecip))
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbMassaG)
                                    .addComponent(rbAltezzaG)
                                    .addComponent(rbUmid)))
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valoreSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xSlider))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(rbVento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeLocalita)))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTemp)
                    .addComponent(rbUmid)
                    .addComponent(jLabel5)
                    .addComponent(nomeLocalita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPress)
                            .addComponent(rbAltezzaG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPrecip)
                            .addComponent(rbMassaG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbVento)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valoreSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xSlider)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valoreSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valoreSliderStateChanged
        // TODO add your handling code here:
        xSlider.setText(""+valoreSlider.getValue());
    }//GEN-LAST:event_valoreSliderStateChanged

    private void tabellaLocalitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellaLocalitaMouseClicked
        // TODO add your handling code here:
        nomeLocalita.setText(tabellaLocalita.getValueAt(tabellaLocalita.getSelectedRow(), 0)
                +", "+tabellaLocalita.getValueAt(tabellaLocalita.getSelectedRow(), 1));
    }//GEN-LAST:event_tabellaLocalitaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int valoreTipo;
        valoreTipo = switch (getSelectedButtonText(gruppoTipoRilevazione)) {
            case "Vento" -> 0;
            case "Umidità" -> 1;
            case "Pressione" -> 2;
            case "Temperatura" -> 3;
            case "Precipitazioni" -> 4;
            case "Altezza dei ghiacciai" -> 5;
            case "Massa dei ghiacciai" -> 6;
            default -> -1;
        };
        try {
            Rilevazione r =new Rilevazione(
                    Utente.getCentro(),
                    Long.valueOf(tabellaLocalita.getValueAt(tabellaLocalita.getSelectedRow(), 2).toString()),
                    valoreTipo,
                    valoreSlider.getValue(),
                    jTextPane1.getText().replace("\n", " ")
            );
            r.salvaRilevazione();
            JOptionPane.showMessageDialog(rootPane, "Registrazione salvata con successo.");
            this.dispose();
        } catch (rilevazioneException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        catch(NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane, "Nessuna area selezionata.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gruppoTipoRilevazione;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel nomeLocalita;
    private javax.swing.JRadioButton rbAltezzaG;
    private javax.swing.JRadioButton rbMassaG;
    private javax.swing.JRadioButton rbPrecip;
    private javax.swing.JRadioButton rbPress;
    private javax.swing.JRadioButton rbTemp;
    private javax.swing.JRadioButton rbUmid;
    private javax.swing.JRadioButton rbVento;
    private javax.swing.JTable tabellaLocalita;
    private javax.swing.JSlider valoreSlider;
    private javax.swing.JLabel xSlider;
    // End of variables declaration//GEN-END:variables
}
