/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClimateMonitoring;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author alesc
 */
public class RilevazionePopup extends javax.swing.JFrame {

    /**
     * Creates new form RilevazionePopup
     */
    public RilevazionePopup() {
        initComponents();
        gruppoTipoRilevazione.add(rbAltezzaG);
        gruppoTipoRilevazione.add(rbMassaG);
        gruppoTipoRilevazione.add(rbPrecip);
        gruppoTipoRilevazione.add(rbPress);
        gruppoTipoRilevazione.add(rbTemp);
        gruppoTipoRilevazione.add(rbUmid);
        gruppoTipoRilevazione.add(rbVento);
        xSlider.setText(""+valoreSlider.getValue());
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        String[] arrayLocalID;
        try {
            FileReader read = new FileReader("datafiles/OperatoriRegistrati.csv");        //legge il file, riga per riga, prende ogni volta una riga in esame
            Scanner input = new Scanner(read);                                                //separa con "#" controlla con la stringa generata solo le 2 posizioni,
            while(input.hasNextLine()) {                                                            //che ci interessano "nome utente e psw".
                String line = input.nextLine();
                String[] parts = line.split("#");
                    if (parts[0].contains(Utente.getCentro()))
                        arrayLocalID=parts[0].split("@");
                }
        }catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(rootPane, "Errore critico: impossibile trovare gli utenti regstrati.");
        }
        
        ArrayList<String[]> datiLocalita= new ArrayList<String[]>();
        //serve ricerca per ID nelle località
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruppoTipoRilevazione = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbTemp = new javax.swing.JRadioButton();
        rbAltezzaG = new javax.swing.JRadioButton();
        rbPress = new javax.swing.JRadioButton();
        rbMassaG = new javax.swing.JRadioButton();
        rbPrecip = new javax.swing.JRadioButton();
        rbVento = new javax.swing.JRadioButton();
        rbUmid = new javax.swing.JRadioButton();
        valoreSlider = new javax.swing.JSlider();
        xSlider = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellaLocalita = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nomeLocalita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Nuova rilevazione");

        rbTemp.setText("Temperatura");

        rbAltezzaG.setText("Altezza dei ghiacciai");

        rbPress.setText("Pressione");

        rbMassaG.setText("Massa dei ghiacciai");

        rbPrecip.setText("Precipitazioni");

        rbVento.setText("Vento");

        rbUmid.setText("Umidità");

        valoreSlider.setMaximum(5);
        valoreSlider.setMinimum(1);
        valoreSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valoreSliderStateChanged(evt);
            }
        });

        xSlider.setText("X");

        jLabel3.setText("Valore:");

        tabellaLocalita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Località", "Stato", "Lat.", "Long."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabellaLocalita.setColumnSelectionAllowed(true);
        tabellaLocalita.getTableHeader().setReorderingAllowed(false);
        tabellaLocalita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellaLocalitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabellaLocalita);
        tabellaLocalita.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabellaLocalita.getColumnModel().getColumnCount() > 0) {
            tabellaLocalita.getColumnModel().getColumn(0).setMinWidth(100);
            tabellaLocalita.getColumnModel().getColumn(0).setPreferredWidth(170);
            tabellaLocalita.getColumnModel().getColumn(0).setMaxWidth(250);
            tabellaLocalita.getColumnModel().getColumn(1).setMinWidth(100);
            tabellaLocalita.getColumnModel().getColumn(1).setPreferredWidth(170);
            tabellaLocalita.getColumnModel().getColumn(1).setMaxWidth(250);
            tabellaLocalita.getColumnModel().getColumn(2).setResizable(false);
            tabellaLocalita.getColumnModel().getColumn(2).setPreferredWidth(70);
            tabellaLocalita.getColumnModel().getColumn(3).setResizable(false);
            tabellaLocalita.getColumnModel().getColumn(3).setPreferredWidth(70);
        }

        jLabel4.setText("Le tue note:");

        jScrollPane2.setViewportView(jTextPane1);

        jLabel5.setText("Località dove è stata effettuata la rilevazione:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Annulla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Invia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbTemp)
                                    .addComponent(rbPress)
                                    .addComponent(rbPrecip))
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbMassaG)
                                    .addComponent(rbAltezzaG)
                                    .addComponent(rbUmid)))
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valoreSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(xSlider))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(rbVento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeLocalita)))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTemp)
                    .addComponent(rbUmid)
                    .addComponent(jLabel5)
                    .addComponent(nomeLocalita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPress)
                            .addComponent(rbAltezzaG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbPrecip)
                            .addComponent(rbMassaG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbVento)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valoreSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xSlider)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valoreSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valoreSliderStateChanged
        // TODO add your handling code here:
        xSlider.setText(""+valoreSlider.getValue());
    }//GEN-LAST:event_valoreSliderStateChanged

    private void tabellaLocalitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellaLocalitaMouseClicked
        // TODO add your handling code here:
        nomeLocalita.setText(tabellaLocalita.getValueAt(tabellaLocalita.getSelectedRow(), 0)
                +", "+tabellaLocalita.getValueAt(tabellaLocalita.getSelectedRow(), 1));
    }//GEN-LAST:event_tabellaLocalitaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RilevazionePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RilevazionePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RilevazionePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RilevazionePopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RilevazionePopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gruppoTipoRilevazione;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel nomeLocalita;
    private javax.swing.JRadioButton rbAltezzaG;
    private javax.swing.JRadioButton rbMassaG;
    private javax.swing.JRadioButton rbPrecip;
    private javax.swing.JRadioButton rbPress;
    private javax.swing.JRadioButton rbTemp;
    private javax.swing.JRadioButton rbUmid;
    private javax.swing.JRadioButton rbVento;
    private javax.swing.JTable tabellaLocalita;
    private javax.swing.JSlider valoreSlider;
    private javax.swing.JLabel xSlider;
    // End of variables declaration//GEN-END:variables
}
